services:
  stalwart:
    image: stalwartlabs/stalwart:latest
    restart: unless-stopped
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "993:993"
    volumes:
      - stalwart-data:/opt/stalwart/data
      - stalwart-etc:/opt/stalwart/etc
      - ./etc/config.toml:/opt/stalwart/etc/config.toml:ro
volumes:
  stalwart-data:
  stalwart-etc:
